In [1]:
import numpy as np

In [2]:
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
x = np.asarray((([1,2,3,4,5,6,7,8], [8,7,6,5,4,3,2,1], [8,7,6,5,4,3,2,1]), ([1,2,3,4,5,6,7,8], [8,7,6,5,4,3,2,1], [8,7,6,5,4,3,2,1])))
x

array([[[1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [8, 7, 6, 5, 4, 3, 2, 1]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [8, 7, 6, 5, 4, 3, 2, 1]]])

In [22]:
x = np.arange(100)
x *= 2
print(x)
x **= 2
print(x)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
[    0     4    16    36    64   100   144   196   256   324   400   484
   576   676   784   900  1024  1156  1296  1444  1600  1764  1936  2116
  2304  2500  2704  2916  3136  3364  3600  3844  4096  4356  4624  4900
  5184  5476  5776  6084  6400  6724  7056  7396  7744  8100  8464  8836
  9216  9604 10000 10404 10816 11236 11664 12100 12544 12996 13456 13924
 14400 14884 15376 15876 16384 16900 17424 17956 18496 19044 19600 20164
 20736 21316 21904 22500 23104 23716 24336 24964 25600 26244 26896 27556
 28224 28900 29584 30276 30976 31684 32400 33124 33856 34596 35344 36100
 36864 37

In [18]:
x = np.random.randn(10, 20)
x

array([[ 4.33128872e-02, -2.11742293e-01, -5.55416912e-01,
        -2.34210946e-01,  5.96624578e-01, -1.28270045e-01,
         1.13664488e+00, -1.41632596e+00,  3.47233246e-01,
         9.74444649e-02, -6.11702713e-01,  2.97624915e-01,
        -2.52537464e-01,  6.74775075e-01, -3.01252171e-01,
        -3.45731912e-02,  1.33412901e+00, -9.15062600e-01,
         3.09944810e-01,  6.05141339e-01],
       [-7.70147926e-01,  1.46975077e+00,  5.63493649e-01,
         8.87415121e-01, -8.20442384e-01,  3.35928083e-01,
         1.59456274e+00,  8.28921119e-01,  5.15966936e-01,
        -1.40010878e-01,  3.04691836e-01,  8.12641640e-01,
         4.97094570e-01, -1.81013931e-01, -1.53543974e-01,
        -1.70271958e+00,  3.47355521e-01, -1.50712786e+00,
         6.69611804e-01,  1.42348128e+00],
       [-2.90370931e-01, -7.74262485e-01, -3.35299273e-01,
        -3.82461824e-01, -6.61240910e-01, -1.66860501e-01,
        -5.36106020e-01, -1.10836660e-01, -1.18739424e+00,
         1.01202592e+00,  9.7

In [27]:
x = np.array([[[1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4]], [[4,3,2,1], [4,3,2,1]]])
print(x)
print(x.ndim)
print(x.shape)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]

 [[4 3 2 1]
  [4 3 2 1]]]
3
(3, 2, 4)


In [36]:
x = np.array([[1 + 9j,2], [3, 4]], dtype=complex)
print(x)

[[1.+9.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [41]:
x = np.linspace(0 + 3j, 10 + 5j, 4, dtype=complex)
x

array([ 0.        +3.j        ,  3.33333333+3.66666667j,
        6.66666667+4.33333333j, 10.        +5.j        ])

In [46]:
x = np.linspace(0, 10, 4, dtype=int)
x

array([ 0,  3,  6, 10])

In [49]:
x = np.ones((3,1))
x

array([[1.],
       [1.],
       [1.]])

In [50]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
x = np.arange(36).reshape(4,9)
y = np.ones_like(x)
y

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
arr1 = np.array([1,2,3,4])
print(arr1)
arr1 = arr1.astype('float64')
print(arr1)

[1 2 3 4]
[1. 2. 3. 4.]


In [63]:
A = np.arange(15).reshape(3,5)
print(A)
print(A[2,3])
print(A[2][3])
print(A[2])
print(A[:,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
13
13
[10 11 12 13 14]
[ 3  8 13]


In [74]:
A = np.arange(24).reshape(2,3,4)
print(A)
print()
print()
print(A[0])
print()
print()
print(A[1])
print()
print()
print(A[:,:,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[ 2  6 10]
 [14 18 22]]
