# Jakies NumPy

In [1]:
import numpy as np

In [2]:
a_arr = np.arange(1_000_000)
print(a_arr)
a_arr = a_arr + 2
print(a_arr)

[     0      1      2 ... 999997 999998 999999]
[      2       3       4 ...  999999 1000000 1000001]


In [3]:
A = np.random.randn(20, 20)
print(A)

[[ 1.50371904e-01 -1.22298274e+00  6.73662177e-01  2.05114958e-01
   6.03792884e-01 -6.37522492e-03  1.27311224e-01 -4.88233795e-01
  -4.50488988e-01  9.72794158e-01  1.04602698e-01  6.71500529e-02
   5.02070444e-01  9.97663247e-01  1.33933400e+00  2.70121260e-02
  -4.25109589e-01  6.53836289e-01 -7.56056905e-01 -8.28792719e-01]
 [-1.92643895e+00  1.70493565e-02  1.10492309e+00 -7.79787037e-01
  -2.98422910e-01 -5.71935016e-01  2.34976773e-01  1.61379371e+00
   1.42643700e+00  5.06935887e-01 -1.08502503e+00  9.85491787e-01
   6.97663445e-01  1.58534665e+00 -3.98367312e-01 -2.93921899e-01
   4.14079782e-01 -1.55422776e+00  1.01818780e+00  1.02219862e-01]
 [-5.42539939e-01  2.06799171e-01  4.57914045e-01  1.88221642e+00
  -6.44138941e-01 -4.53637550e-03  3.72994536e-01 -8.55655751e-01
  -9.23640155e-01  1.27636704e+00  4.29796219e-01 -6.98607225e-01
   6.11762131e-01  1.66603458e+00  3.40882229e-01  1.98270157e-01
  -9.92448729e-01  6.03902302e-02 -2.20581176e+00  1.71881438e-01]
 [-3.06

In [4]:
x = np.array([1,2,3]) # tablica jednowymiarowa
A = np.array([[1,2,3] , [4,5,6]]) # tablica dwuwymiarowa
B = np.array( [[[1,1,1],[1,1,1]], [[2,2,2],[2,2,2]]]) # wielowymiarowa
print(x.ndim, " ", A.ndim, " ", B.ndim)
print(B.shape)

1   2   3
(2, 2, 3)


In [5]:
z = np.array( [[1,0], [0,1]], dtype=complex) # tablica liczb zespolonych
print(z)
print(z.shape)

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
(2, 2)


In [6]:
for n in np.linspace(0., 10., 3):
    print(n)

0.0
5.0
10.0


In [7]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
arr = np.array(['12', '-0.1', '2.3'])
arr.astype(float)

array([12. , -0.1,  2.3])

In [9]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
A = np.arange(20).reshape(5,4)
print(A[2:4], '\n') # wiersze od trzeciego do czwartego
print(A[:,2:4], '\n') # trzecia i czwarta kolumnę
print(A[:,[2,3]]) # równoważnie

[[ 8  9 10 11]
 [12 13 14 15]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


In [11]:
A = np.arange(4).reshape((2,2))
x = np.array([1,2])
print(A)
print(x)
print(A * x)

[[0 1]
 [2 3]]
[1 2]
[[0 2]
 [2 6]]


In [12]:
A = np.arange(5, 20).reshape((5, 3))
x = np.array([1,100,1])
A < x

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [13]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((y, x), axis=0), '\n')
print(np.vstack((y,x)), '\n')

[[5 6]
 [1 2]
 [3 4]] 

[[5 6]
 [1 2]
 [3 4]] 



In [27]:
print(np.random.choice(5, 5, replace=False), '\n')

[2 1 4 0 3] 



In [34]:
A = np.arange(6).reshape(2,3)
print(A)
print()
print(A[:, np.newaxis, :])
print()
print(A[np.newaxis, :, :])
print()
print(A[:, np.newaxis, :] - A[np.newaxis, :, :])

[[0 1 2]
 [3 4 5]]

[[[0 1 2]]

 [[3 4 5]]]

[[[0 1 2]
  [3 4 5]]]

[[[ 0  0  0]
  [-3 -3 -3]]

 [[ 3  3  3]
  [ 0  0  0]]]
